import { Lead } from "@/types";

export const mockLeads: Lead[] = [
  {
    id: "L001",
    customer: {
      name: "Rajesh Kumar",
      phone: "+91 98765 43210",
      alternatePhone: "+91 98765 43211",
      email: "rajesh.kumar@email.com",
      city: "Ahmedabad",
      source: "Website",
      assignedSalesExecutive: "Amit Sharma",
    },
    vehicle: {
      brand: "Maruti Suzuki",
      model: "Swift",
      variant: "VXI",
      registrationNumber: "MH-02-AB-1234",
      registrationYear: 2019,
      fuelType: "Petrol",
      transmission: "Manual",
      kmsDriven: 45000,
      ownership: 1,
      insuranceValidTill: "2024-12-31",
      expectedPrice: 550000,
    },
    valuation: {
      status: "Completed",
      assignedValuer: "Prakash Joshi",
      inspectionDate: "2024-01-10",
      estimatedPrice: 525000,
      finalOfferPrice: 515000,
      notes: "Good condition, minor scratches on bumper",
    },
    internal: {
      relationshipManager: "Sneha Patel",
      followUpDates: ["2024-01-15", "2024-01-20"],
      callNotes: ["Customer interested", "Waiting for better offer"],
      documentStatus: "Completed",
      approvalStatus: "Approved",
    },
    status: "Negotiation",
    createdAt: "2024-01-05T10:30:00Z",
    updatedAt: "2024-01-12T14:20:00Z",
  },
  {
    id: "L002",
    customer: {
      name: "Priya Sharma",
      phone: "+91 87654 32109",
      email: "priya.s@email.com",
      city: "Surat",
      source: "Call",
      assignedSalesExecutive: "Vikram Singh",
    },
    vehicle: {
      brand: "Hyundai",
      model: "i20",
      variant: "Sportz",
      registrationNumber: "DL-05-CD-5678",
      registrationYear: 2020,
      fuelType: "Diesel",
      transmission: "Manual",
      kmsDriven: 32000,
      ownership: 1,
      insuranceValidTill: "2025-03-15",
      expectedPrice: 750000,
    },
    valuation: {
      status: "Scheduled",
      assignedValuer: "Rahul Mehta",
      inspectionDate: "2024-01-18",
    },
    internal: {
      followUpDates: ["2024-01-16"],
      callNotes: ["Initial contact made", "Scheduled valuation"],
      documentStatus: "Pending",
      approvalStatus: "Pending",
    },
    status: "Valuation Scheduled",
    createdAt: "2024-01-12T09:15:00Z",
    updatedAt: "2024-01-12T09:15:00Z",
  },
  {
    id: "L003",
    customer: {
      name: "Amit Patel",
      phone: "+91 76543 21098",
      alternatePhone: "+91 76543 21099",
      email: "amit.patel@email.com",
      city: "Vadodara",
      source: "Walk-in",
      assignedSalesExecutive: "Rohan Kumar",
    },
    vehicle: {
      brand: "Honda",
      model: "City",
      variant: "VX",
      registrationNumber: "KA-01-MN-9012",
      registrationYear: 2018,
      fuelType: "Petrol",
      transmission: "Automatic",
      kmsDriven: 58000,
      ownership: 2,
      insuranceValidTill: "2024-06-30",
      expectedPrice: 820000,
    },
    valuation: {
      status: "Completed",
      assignedValuer: "Prakash Joshi",
      inspectionDate: "2024-01-08",
      estimatedPrice: 780000,
      finalOfferPrice: 775000,
      notes: "Excellent condition, well maintained",
    },
    internal: {
      relationshipManager: "Kavita Reddy",
      followUpDates: ["2024-01-14", "2024-01-19"],
      callNotes: ["Very interested", "Wants to see other options"],
      documentStatus: "Completed",
      approvalStatus: "Approved",
    },
    status: "Closed",
    createdAt: "2024-01-06T11:00:00Z",
    updatedAt: "2024-01-12T16:45:00Z",
  },
  {
    id: "L004",
    customer: {
      name: "Sneha Gupta",
      phone: "+91 65432 10987",
      email: "sneha.g@email.com",
      city: "Rajkot",
      source: "Partner",
      assignedSalesExecutive: "Amit Sharma",
    },
    vehicle: {
      brand: "Tata",
      model: "Nexon",
      variant: "XZ+",
      registrationNumber: "MH-12-EF-3456",
      registrationYear: 2021,
      fuelType: "Electric",
      transmission: "Automatic",
      kmsDriven: 18000,
      ownership: 1,
      insuranceValidTill: "2025-09-20",
      expectedPrice: 1200000,
    },
    valuation: {
      status: "Pending",
    },
    internal: {
      followUpDates: [],
      callNotes: ["New lead from partner"],
      documentStatus: "Pending",
      approvalStatus: "Pending",
    },
    status: "New",
    createdAt: "2024-01-12T16:00:00Z",
    updatedAt: "2024-01-12T16:00:00Z",
  },
  {
    id: "L005",
    customer: {
      name: "Vikas Malhotra",
      phone: "+91 54321 09876",
      alternatePhone: "+91 54321 09877",
      email: "vikas.m@email.com",
      city: "Bhavnagar",
      source: "Website",
      assignedSalesExecutive: "Vikram Singh",
    },
    vehicle: {
      brand: "Mahindra",
      model: "XUV500",
      variant: "W8",
      registrationNumber: "TS-09-GH-7890",
      registrationYear: 2017,
      fuelType: "Diesel",
      transmission: "Manual",
      kmsDriven: 78000,
      ownership: 1,
      insuranceValidTill: "2024-04-15",
      expectedPrice: 950000,
    },
    valuation: {
      status: "Completed",
      assignedValuer: "Rahul Mehta",
      inspectionDate: "2024-01-09",
      estimatedPrice: 890000,
      finalOfferPrice: 850000,
      notes: "High mileage, needs some maintenance work",
    },
    internal: {
      relationshipManager: "Sneha Patel",
      followUpDates: ["2024-01-16"],
      callNotes: ["Customer not happy with offer", "Needs higher price"],
      documentStatus: "Completed",
      approvalStatus: "Rejected",
    },
    status: "Rejected",
    createdAt: "2024-01-07T13:30:00Z",
    updatedAt: "2024-01-11T10:20:00Z",
  },
  {
    id: "L006",
    customer: {
      name: "Kiran Shah",
      phone: "+91 98765 12345",
      email: "kiran.shah@email.com",
      city: "Gandhinagar",
      source: "Website",
      assignedSalesExecutive: "Rohan Kumar",
    },
    vehicle: {
      brand: "Toyota",
      model: "Fortuner",
      variant: "4X4 AT",
      registrationNumber: "GJ-01-AB-1234",
      registrationYear: 2020,
      fuelType: "Diesel",
      transmission: "Automatic",
      kmsDriven: 35000,
      ownership: 1,
      insuranceValidTill: "2025-06-15",
      expectedPrice: 3200000,
    },
    valuation: {
      status: "Scheduled",
      assignedValuer: "Prakash Joshi",
      inspectionDate: new Date().toISOString().split('T')[0],
    },
    internal: {
      followUpDates: [new Date().toISOString().split('T')[0]],
      callNotes: ["Premium SUV, excellent condition"],
      documentStatus: "Pending",
      approvalStatus: "Pending",
    },
    status: "Valuation Scheduled",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "L007",
    customer: {
      name: "Nisha Desai",
      phone: "+91 98765 23456",
      alternatePhone: "+91 98765 23457",
      email: "nisha.d@email.com",
      city: "Anand",
      source: "Call",
      assignedSalesExecutive: "Amit Sharma",
    },
    vehicle: {
      brand: "Kia",
      model: "Seltos",
      variant: "HTX",
      registrationNumber: "GJ-05-XY-5678",
      registrationYear: 2021,
      fuelType: "Petrol",
      transmission: "Manual",
      kmsDriven: 28000,
      ownership: 1,
      insuranceValidTill: "2025-08-20",
      expectedPrice: 1350000,
    },
    valuation: {
      status: "Completed",
      assignedValuer: "Rahul Mehta",
      inspectionDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString().split('T')[0],
      estimatedPrice: 1320000,
      finalOfferPrice: 1300000,
      notes: "Good condition, minor wear on seats",
    },
    internal: {
      relationshipManager: "Kavita Reddy",
      followUpDates: [new Date().toISOString().split('T')[0]],
      callNotes: ["Customer considering offer"],
      documentStatus: "Completed",
      approvalStatus: "Approved",
    },
    status: "Negotiation",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "L008",
    customer: {
      name: "Mehul Joshi",
      phone: "+91 98765 34567",
      email: "mehul.j@email.com",
      city: "Jamnagar",
      source: "Partner",
      assignedSalesExecutive: "Vikram Singh",
    },
    vehicle: {
      brand: "Volkswagen",
      model: "Polo",
      variant: "Highline Plus",
      registrationNumber: "GJ-10-CD-9012",
      registrationYear: 2019,
      fuelType: "Petrol",
      transmission: "Manual",
      kmsDriven: 52000,
      ownership: 1,
      insuranceValidTill: "2024-11-30",
      expectedPrice: 680000,
    },
    valuation: {
      status: "Completed",
      assignedValuer: "Prakash Joshi",
      inspectionDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString().split('T')[0],
      estimatedPrice: 660000,
      finalOfferPrice: 650000,
      notes: "Well maintained, good service history",
    },
    internal: {
      relationshipManager: "Sneha Patel",
      followUpDates: [],
      callNotes: ["Deal closed successfully"],
      documentStatus: "Completed",
      approvalStatus: "Approved",
    },
    status: "Closed",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
  },
  {
    id: "L009",
    customer: {
      name: "Pooja Rao",
      phone: "+91 98765 45678",
      city: "Navsari",
      source: "Walk-in",
      assignedSalesExecutive: "Rohan Kumar",
    },
    vehicle: {
      brand: "Renault",
      model: "Duster",
      variant: "RXZ",
      registrationNumber: "GJ-12-EF-3456",
      registrationYear: 2018,
      fuelType: "Diesel",
      transmission: "Manual",
      kmsDriven: 68000,
      ownership: 2,
      insuranceValidTill: "2024-10-15",
      expectedPrice: 720000,
    },
    valuation: {
      status: "Pending",
    },
    internal: {
      followUpDates: [],
      callNotes: ["Initial inquiry made"],
      documentStatus: "Pending",
      approvalStatus: "Pending",
    },
    status: "New",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
  },
  {
    id: "L010",
    customer: {
      name: "Arjun Modi",
      phone: "+91 98765 56789",
      alternatePhone: "+91 98765 56790",
      email: "arjun.modi@email.com",
      city: "Morbi",
      source: "Website",
      assignedSalesExecutive: "Amit Sharma",
    },
    vehicle: {
      brand: "Nissan",
      model: "Magnite",
      variant: "XV Premium",
      registrationNumber: "GJ-15-GH-7890",
      registrationYear: 2022,
      fuelType: "Petrol",
      transmission: "Automatic",
      kmsDriven: 15000,
      ownership: 1,
      insuranceValidTill: "2026-01-10",
      expectedPrice: 950000,
    },
    valuation: {
      status: "Scheduled",
      assignedValuer: "Rahul Mehta",
      inspectionDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 2).toISOString().split('T')[0],
    },
    internal: {
      followUpDates: [new Date(Date.now() + 1000 * 60 * 60 * 24 * 1).toISOString().split('T')[0]],
      callNotes: ["Customer wants quick sale"],
      documentStatus: "Pending",
      approvalStatus: "Pending",
    },
    status: "Contacted",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: "L011",
    customer: {
      name: "Divya Thakkar",
      phone: "+91 98765 67890",
      email: "divya.t@email.com",
      city: "Mehsana",
      source: "Call",
      assignedSalesExecutive: "Vikram Singh",
    },
    vehicle: {
      brand: "Skoda",
      model: "Rapid",
      variant: "Ambition",
      registrationNumber: "GJ-02-IJ-1122",
      registrationYear: 2017,
      fuelType: "Diesel",
      transmission: "Manual",
      kmsDriven: 75000,
      ownership: 1,
      insuranceValidTill: "2024-12-31",
      expectedPrice: 580000,
    },
    valuation: {
      status: "Completed",
      assignedValuer: "Prakash Joshi",
      inspectionDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString().split('T')[0],
      estimatedPrice: 550000,
      finalOfferPrice: 540000,
      notes: "Average condition, needs minor repairs",
    },
    internal: {
      relationshipManager: "Sneha Patel",
      followUpDates: [],
      callNotes: ["Customer rejected offer"],
      documentStatus: "Completed",
      approvalStatus: "Rejected",
    },
    status: "Rejected",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
  },
  {
    id: "L012",
    customer: {
      name: "Harsh Pandya",
      phone: "+91 98765 78901",
      city: "Bharuch",
      source: "Partner",
      assignedSalesExecutive: "Rohan Kumar",
    },
    vehicle: {
      brand: "MG",
      model: "Hector",
      variant: "Sharp",
      registrationNumber: "GJ-18-KL-2233",
      registrationYear: 2021,
      fuelType: "Petrol",
      transmission: "Automatic",
      kmsDriven: 22000,
      ownership: 1,
      insuranceValidTill: "2025-09-15",
      expectedPrice: 1650000,
    },
    valuation: {
      status: "Completed",
      assignedValuer: "Rahul Mehta",
      inspectionDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString().split('T')[0],
      estimatedPrice: 1620000,
      finalOfferPrice: 1600000,
      notes: "Excellent condition, like new",
    },
    internal: {
      relationshipManager: "Kavita Reddy",
      followUpDates: [],
      callNotes: ["Deal successfully closed"],
      documentStatus: "Completed",
      approvalStatus: "Approved",
    },
    status: "Closed",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 18).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString(),
  },
  {
    id: "L013",
    customer: {
      name: "Ritu Vora",
      phone: "+91 98765 89012",
      alternatePhone: "+91 98765 89013",
      email: "ritu.vora@email.com",
      city: "Vapi",
      source: "Website",
      assignedSalesExecutive: "Amit Sharma",
    },
    vehicle: {
      brand: "Ford",
      model: "EcoSport",
      variant: "Titanium",
      registrationNumber: "GJ-20-MN-3344",
      registrationYear: 2019,
      fuelType: "Diesel",
      transmission: "Manual",
      kmsDriven: 48000,
      ownership: 1,
      insuranceValidTill: "2025-03-20",
      expectedPrice: 850000,
    },
    valuation: {
      status: "Completed",
      assignedValuer: "Prakash Joshi",
      inspectionDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString().split('T')[0],
      estimatedPrice: 830000,
      finalOfferPrice: 820000,
    },
    internal: {
      relationshipManager: "Sneha Patel",
      followUpDates: [],
      callNotes: ["Customer accepted offer"],
      documentStatus: "Completed",
      approvalStatus: "Approved",
    },
    status: "Valuation Completed",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 22).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 19).toISOString(),
  },
  {
    id: "L014",
    customer: {
      name: "Yash Trivedi",
      phone: "+91 98765 90123",
      email: "yash.trivedi@email.com",
      city: "Palanpur",
      source: "Walk-in",
      assignedSalesExecutive: "Vikram Singh",
    },
    vehicle: {
      brand: "Jeep",
      model: "Compass",
      variant: "Limited Plus",
      registrationNumber: "GJ-08-OP-4455",
      registrationYear: 2020,
      fuelType: "Diesel",
      transmission: "Automatic",
      kmsDriven: 38000,
      ownership: 1,
      insuranceValidTill: "2025-07-30",
      expectedPrice: 2100000,
    },
    valuation: {
      status: "Scheduled",
      assignedValuer: "Rahul Mehta",
      inspectionDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 3).toISOString().split('T')[0],
    },
    internal: {
      followUpDates: [new Date(Date.now() + 1000 * 60 * 60 * 24 * 2).toISOString().split('T')[0]],
      callNotes: ["Premium vehicle inquiry"],
      documentStatus: "Pending",
      approvalStatus: "Pending",
    },
    status: "Valuation Scheduled",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
  },
  {
    id: "L015",
    customer: {
      name: "Kavya Solanki",
      phone: "+91 98766 01234",
      city: "Bhuj",
      source: "Call",
      assignedSalesExecutive: "Rohan Kumar",
    },
    vehicle: {
      brand: "Chevrolet",
      model: "Beat",
      variant: "LT",
      registrationNumber: "GJ-11-QR-5566",
      registrationYear: 2016,
      fuelType: "Petrol",
      transmission: "Manual",
      kmsDriven: 62000,
      ownership: 2,
      insuranceValidTill: "2024-08-15",
      expectedPrice: 320000,
    },
    valuation: {
      status: "Pending",
    },
    internal: {
      followUpDates: [],
      callNotes: ["Initial contact made"],
      documentStatus: "Pending",
      approvalStatus: "Pending",
    },
    status: "New",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
  },
];
