import { Lead } from "@/types";

export const mockLeads: Lead[] = [
  {
    id: "L001",
    customer: {
      name: "Rajesh Kumar",
      phone: "+91 98765 43210",
      alternatePhone: "+91 98765 43211",
      email: "rajesh.kumar@email.com",
      city: "Mumbai",
      source: "Website",
      assignedSalesExecutive: "Amit Sharma",
    },
    vehicle: {
      brand: "Maruti Suzuki",
      model: "Swift",
      variant: "VXI",
      registrationNumber: "MH-02-AB-1234",
      registrationYear: 2019,
      fuelType: "Petrol",
      transmission: "Manual",
      kmsDriven: 45000,
      ownership: 1,
      insuranceValidTill: "2024-12-31",
      expectedPrice: 550000,
    },
    valuation: {
      status: "Completed",
      assignedValuer: "Prakash Joshi",
      inspectionDate: "2024-01-10",
      estimatedPrice: 525000,
      finalOfferPrice: 515000,
      notes: "Good condition, minor scratches on bumper",
    },
    internal: {
      relationshipManager: "Sneha Patel",
      followUpDates: ["2024-01-15", "2024-01-20"],
      callNotes: ["Customer interested", "Waiting for better offer"],
      documentStatus: "Completed",
      approvalStatus: "Approved",
    },
    status: "Negotiation",
    createdAt: "2024-01-05T10:30:00Z",
    updatedAt: "2024-01-12T14:20:00Z",
  },
  {
    id: "L002",
    customer: {
      name: "Priya Sharma",
      phone: "+91 87654 32109",
      email: "priya.s@email.com",
      city: "Delhi",
      source: "Call",
      assignedSalesExecutive: "Vikram Singh",
    },
    vehicle: {
      brand: "Hyundai",
      model: "i20",
      variant: "Sportz",
      registrationNumber: "DL-05-CD-5678",
      registrationYear: 2020,
      fuelType: "Diesel",
      transmission: "Manual",
      kmsDriven: 32000,
      ownership: 1,
      insuranceValidTill: "2025-03-15",
      expectedPrice: 750000,
    },
    valuation: {
      status: "Scheduled",
      assignedValuer: "Rahul Mehta",
      inspectionDate: "2024-01-18",
    },
    internal: {
      followUpDates: ["2024-01-16"],
      callNotes: ["Initial contact made", "Scheduled valuation"],
      documentStatus: "Pending",
      approvalStatus: "Pending",
    },
    status: "Valuation Scheduled",
    createdAt: "2024-01-12T09:15:00Z",
    updatedAt: "2024-01-12T09:15:00Z",
  },
  {
    id: "L003",
    customer: {
      name: "Amit Patel",
      phone: "+91 76543 21098",
      alternatePhone: "+91 76543 21099",
      email: "amit.patel@email.com",
      city: "Bangalore",
      source: "Walk-in",
      assignedSalesExecutive: "Rohan Kumar",
    },
    vehicle: {
      brand: "Honda",
      model: "City",
      variant: "VX",
      registrationNumber: "KA-01-MN-9012",
      registrationYear: 2018,
      fuelType: "Petrol",
      transmission: "Automatic",
      kmsDriven: 58000,
      ownership: 2,
      insuranceValidTill: "2024-06-30",
      expectedPrice: 820000,
    },
    valuation: {
      status: "Completed",
      assignedValuer: "Prakash Joshi",
      inspectionDate: "2024-01-08",
      estimatedPrice: 780000,
      finalOfferPrice: 775000,
      notes: "Excellent condition, well maintained",
    },
    internal: {
      relationshipManager: "Kavita Reddy",
      followUpDates: ["2024-01-14", "2024-01-19"],
      callNotes: ["Very interested", "Wants to see other options"],
      documentStatus: "Completed",
      approvalStatus: "Approved",
    },
    status: "Closed",
    createdAt: "2024-01-06T11:00:00Z",
    updatedAt: "2024-01-12T16:45:00Z",
  },
  {
    id: "L004",
    customer: {
      name: "Sneha Gupta",
      phone: "+91 65432 10987",
      email: "sneha.g@email.com",
      city: "Pune",
      source: "Partner",
      assignedSalesExecutive: "Amit Sharma",
    },
    vehicle: {
      brand: "Tata",
      model: "Nexon",
      variant: "XZ+",
      registrationNumber: "MH-12-EF-3456",
      registrationYear: 2021,
      fuelType: "Electric",
      transmission: "Automatic",
      kmsDriven: 18000,
      ownership: 1,
      insuranceValidTill: "2025-09-20",
      expectedPrice: 1200000,
    },
    valuation: {
      status: "Pending",
    },
    internal: {
      followUpDates: [],
      callNotes: ["New lead from partner"],
      documentStatus: "Pending",
      approvalStatus: "Pending",
    },
    status: "New",
    createdAt: "2024-01-12T16:00:00Z",
    updatedAt: "2024-01-12T16:00:00Z",
  },
  {
    id: "L005",
    customer: {
      name: "Vikas Malhotra",
      phone: "+91 54321 09876",
      alternatePhone: "+91 54321 09877",
      email: "vikas.m@email.com",
      city: "Hyderabad",
      source: "Website",
      assignedSalesExecutive: "Vikram Singh",
    },
    vehicle: {
      brand: "Mahindra",
      model: "XUV500",
      variant: "W8",
      registrationNumber: "TS-09-GH-7890",
      registrationYear: 2017,
      fuelType: "Diesel",
      transmission: "Manual",
      kmsDriven: 78000,
      ownership: 1,
      insuranceValidTill: "2024-04-15",
      expectedPrice: 950000,
    },
    valuation: {
      status: "Completed",
      assignedValuer: "Rahul Mehta",
      inspectionDate: "2024-01-09",
      estimatedPrice: 890000,
      finalOfferPrice: 850000,
      notes: "High mileage, needs some maintenance work",
    },
    internal: {
      relationshipManager: "Sneha Patel",
      followUpDates: ["2024-01-16"],
      callNotes: ["Customer not happy with offer", "Needs higher price"],
      documentStatus: "Completed",
      approvalStatus: "Rejected",
    },
    status: "Rejected",
    createdAt: "2024-01-07T13:30:00Z",
    updatedAt: "2024-01-11T10:20:00Z",
  },
];
